---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: actual-budget-openid-secret
  namespace: actual
spec:
  encryptedData:
    CLIENT_SECRET: AgDHFri/UnpkS96TYHCSGK1MsZPY4M/WtvRvHSFSIhLrQxts4j7M/Yf9o3PYT/5x3SFNsxjAv4EQPRUB/tXK2DRM4kUEgmnAnSEv9WhAuMb2+VG4zR1Gm49BhfyNJrvrw5MqKAYD6R3HwBUYKdOZD5JHUCdBYeQaX9RvaQV+IbRKjPJjhcISlQSoU5lhVxugEJA8OSwAqIOpWPG4ggyspvAO+ITsQP2NQfQSMCTiCPCacGwWbWi/V/Eft+TE4DQ7WSmeNq/GK5u9eFGT8tUzzrGx1zKPWRQOU4cgalu9vdifVNW3tdx4M4hF1pZVjiYFf+cRASST9TAeAyVut8gUtaHDmCv/IETkVcNAfBMKSZ5Sin8gKGtIAeNSWRUkw8T0Wtbr+31QGSEJCCetHQPJbY6s990kb4i3x4wXGby5sZG7pKW+SerMPMt7w35gLKpuV0J3c9AYbsK2jG5vZBWAHnlBksXyXrPcG3qCdz3kRaVRw5IEdg91rj3Z1RqfcD5MOkz9xTm3LVw0MggZtpdOfqWXEwvUMzSHDYLcAhWanZ9FHsOY+lR4W5yGmblTyx3T+0FKdAKE8TtI3/1hDB/J6EtwVC6nr0yGg+isbufUc0ThkUKbgWVzbqdj6ADkCpEQXeZC1JvYTaxdv1Nlz77dWTQQlRxrJXZjPdDPFmAHMuFtu4fgQI7Bji5TD8nFj8Jyayy7Fm9au6nEWRC+ALRxfknx3tf8W9irxnIubCr421Sj/ijBW/bt5L39tLZ6ENesZh3/2a/SuKsba0P5wvtt+JZWJD1NL76c6+ZUJ281FZhwJu891RSWvVT0enWTMwyEWYd9U47o+dTsPnn5xjuHTMrLXHDuSOV5EaM9B6BOuO0Z1g==
  template:
    metadata:
      creationTimestamp: null
      name: actual-budget-openid-secret
      namespace: actual
