password:
  create: false
  existingSecret: "pihole-web-password"
  existingSecretKey: "admin-password"

config:
  timezone: "Asia/Dubai"


services:
  dns:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 10.5.1.53

ingress:
  enabled: true 
  className: "traefik" 
  host: "pihole.cubancodelab.net" 
  tls:
    enabled: true
    secretName: "pihole-tls"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
