apiVersion: v2
name: media
description: A Helm umbrella chart for media management stack (Jellyfin, Radarr, Sonarr, Seerr, Prowlarr, qBittorrent, Bazarr, Flaresolverr)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: jellyfin
    version: 0.2.0
    repository: https://helms.cubancodelab.net/
    condition: jellyfin.enabled
  - name: radarr
    version: 0.2.2
    repository: https://helms.cubancodelab.net/
    condition: radarr.enabled
  - name: sonarr
    version: 0.1.2
    repository: https://helms.cubancodelab.net/
    condition: sonarr.enabled
  - name: seerr
    version: 0.1.5
    repository: https://helms.cubancodelab.net/
    condition: seerr.enabled
  - name: prowlarr
    version: 0.1.2
    repository: https://helms.cubancodelab.net/
    condition: prowlarr.enabled
  - name: qbittorrent
    version: 0.4.1
    repository: https://helms.cubancodelab.net/
    condition: qbittorrent.enabled
  - name: flaresolverr
    version: 1.0.0
    repository: https://helms.cubancodelab.net/
    condition: flaresolverr.enabled
  - name: bazarr
    version: 0.1.2
    repository: https://helms.cubancodelab.net/
    condition: bazarr.enabled
  - name: transmission-openvpn
    version: 0.1.0
    repository: https://helms.cubancodelab.net/
    condition: transmission-openvpn.enabled