---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    password: AgA+pnpNf/qn2JPeQ1Y95Dulft0ruOn6omaeyl12ahyyJmpqyGrDHnMTNW0aaK2nIqORjs4fU74Vq+bdLFsmmqA6CaWcnkaoIWXh0SqDIFqE3OygIFNCbfZEsnMZKYZG2FhttqJFdh0FHB3j8xRCMvUEHUV+9TrMjvzsMb7zNlnykdJuaDmVziWKKTKDMXTTqN9kBryncJ0nKBsxZ2bHPwF/1KphOjDTPsLxrykoqKNBM8R28OJtrPJlLtcLgmJZg/D+k0yoKAhXluyUcVe/GAM4PUatTfsgdLqyE7T8qal2mwwP5mUKk5unFZDEwmrT4FbOcrhRfdFpLijiTKxxQWoxWBIOZpspTC85R2b63o5vAXksTwNxmtd6lTPLUlID0RIcxMXLTSsDf3kgA20GvGqy9giePl3icO0OtYmvpn0aZ+r1EkUD6e1pbU3s7jlrCZYvmF5gr3vto4Yfeuqiv4ofXuEQ/RQr0Ezmui60cGLSfaNqppZ+V+Xolp1Z4N/hbzqcgZka1C7lfmLly5+kkbtEIiKhOhjI8roYCvzKXwgie3IV4AjxiJyJbk4nx6fAYs8a47+cFUcocVL2wKW4YN6s7F5ym9qSHr/hruLajfDVMFmClw4MDMHM7jVfJyqBVMwZrb/6XZRYUSfTCswGJ7t6mQlvOwsnz56/VvAnCtDXdRfZghGjIGLDBfruZy5fpTJvQ28gQbaFu4If1lr6UdKZCz7EAenngtpA
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: database
