---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    password: AgDOppsNphY6xmF8dzmqfsCsXqEShvmZyRIuIxfCXEWbdmIkBcn7zYEoV+lwyasnKhlUUh4wV2btsHUePslp1Tv8H5vOa9ehzM9i3bbeR3sdh+ezexro8P4ZkTVdcGOYU3ipEVrvkfXbmTRgXBy0qQXkWkNLN6I6N9HnpHyDX8UwihLidLUmNYIx2/6+ScDzzBvjwZgvMBdY1zpJ2A6dFHMOk1RJg4dTEHE9+tlsM0I3MemxkQqenYZx5+nWvwvNFhO71ZWa74z7XN5Vepy0wJxaopie90mV+WZUCaMrln8/HqQXStA2UVoIpp7Dnmnqt8ykD3Y+fG3TXvxFm4I0JGbWFv3LPHhhjtRZdvBwjoVPkl6m0ejtwjLprAEhQh7vJJEGTK99SYasx67iSn8i5IJEqHjjdPjVWi2pjEfuVdn/6/uOgg9SwzH40WPuH5tscGrGL2gpXxoBpyb1SG33yfZoziryYH7ezhYibBIJwRZTOodjj6rXMxWF1quwpB+fhud1mniKrNXzjg8JfxKJIIZ6z0nOSKRepw+M1QNj9ScP4Eq6KLFEmUoW5dTg9Ty5ljfshkiBKPS8MopWBSLsIlJiI05dufSzMHQ2jEK/HQ9LRy/CLfWFIBy8n6EpN+rEP4D1g3n//kBIBCK9rshSys92WtGR2C05Qk/lvAvt8JHS3Tc1OChXXr711akTKzg7vq+8yVNCVtT6BidXL5rWnZ65gKQgf1Jj7mfN
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: database
