global:
  imageRegistry: public.ecr.aws
  postgresql:
    auth:
      existingSecret: postgresql-secret
      secretKeys:
        adminPasswordKey: password
        userPasswordKey: password

auth:
  username: postgres
  database: postgres
  password: ""
  existingSecret: postgresql-secret
  secretKeys:
    adminPasswordKey: password
    userPasswordKey: password

primary:
  image:
    registry: public.ecr.aws
    repository: bitnami/postgresql
    tag: 16.2.0-debian-12-r15
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn-2replicas

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  initdb:
    scripts:
      init.sql: |
        -- Create default user for applications
        -- Additional databases and users will be created as needed

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

volumePermissions:
  enabled: false
